// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Produto struct {
	ID        int32     `json:"id"`
	Nome      string    `json:"nome"`
	Descricao string    `json:"descricao"`
	Preco     int32     `json:"preco"`
	CriadoEm  time.Time `json:"criado_em"`
}
