// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateProdutos(ctx context.Context, arg CreateProdutosParams) (Produto, error)
	DeleteProduto(ctx context.Context, id int32) error
	GetProduto(ctx context.Context, id int32) (Produto, error)
	ListProdutos(ctx context.Context) ([]Produto, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) error
}

var _ Querier = (*Queries)(nil)
